package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"regexp"
	"time"

	"net/http"

	"github.com/gocarina/gocsv"
)

const (
	allDayHours = "[0-2][0-9]"
)

func hello() string {
	return "world"
}

func readURL(u string) ([]byte, error) {
	var bodyBytes []byte

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	req, err := http.NewRequest("GET", u, nil)
	if err != nil {
		return nil, err
	}

	// Required to parse Reddit feeds
	req.Header.Set("user-agent", "hello:world:v0.0 (by /u/ocelost)")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	//https://stackoverflow.com/a/38673698/2777965
	if resp.StatusCode == http.StatusOK {
		bodyBytes, err = ioutil.ReadAll(resp.Body)
		if err != nil {
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("StatusCode not 200, but '%v'", resp.StatusCode)
	}
	return bodyBytes, nil
}

type feed struct {
	Feed  xml.Name `xml:"feed"`
	Entry []Entry  `xml:"entry"`
}
type Entry struct {
	XMLName xml.Name `xml:"entry"`
	Updated string   `xml:"updated"`
	Title   string   `xml:"title"`
	Link    Link     `xml:"link"`
}
type Link struct {
	Href string `xml:"href,attr"`
}

type rss struct {
	XMLName xml.Name `xml:"rss"`
	Item    []Item   `xml:"channel>item"`
}
type Item struct {
	XMLName xml.Name `xml:"item"`
	PubDate string   `xml:"pubDate"`
	Title   string   `xml:"title"`
	Link    string   `xml:"link"`
}

func atom(dateStr string, u string) error {
	b, err := readURL(u)
	if err != nil {
		return err
	}
	var f feed
	if err = xml.Unmarshal(b, &f); err != nil {
		return err
	}
	for i := 0; i < len(f.Entry); i++ {
		updated := f.Entry[i].Updated
		match, err := regexp.MatchString(dateStr, updated)
		if err != nil {
			return err
		}
		if match {
			fmt.Println(updated + " " + f.Entry[i].Title + " " + f.Entry[i].Link.Href)
		}
	}
	return nil
}

func standard(dateStr string, u string) error {
	b, err := readURL(u)
	if err != nil {
		return err
	}
	var r rss
	if err = xml.Unmarshal(b, &r); err != nil {
		return err
	}
	for i := 0; i < len(r.Item); i++ {
		pubDate := r.Item[i].PubDate
		match, err := regexp.MatchString(dateStr, pubDate)
		if err != nil {
			return err
		}
		if match {
			fmt.Println(pubDate + " " + r.Item[i].Title + " " + r.Item[i].Link)
		}
	}
	return nil
}

type RSSFeeds struct {
	Type string `csv:"type"`
	URL  string `csv:"url"`
}

func csv(f string) ([]*RSSFeeds, error) {
	u, err := os.OpenFile(f, os.O_RDWR|os.O_CREATE, os.ModePerm)
	if err != nil {
		return nil, err
	}
	defer u.Close()

	r := []*RSSFeeds{}

	if err := gocsv.UnmarshalFile(u, &r); err != nil {
		return nil, err
	}
	return r, err
}

func read(urls []*RSSFeeds, date string) error {
	for _, u := range urls {
		switch t := u.Type; t {
		case "atom":
			if err := atom(date, u.URL); err != nil {
				return err
			}
		case "standard":
			if err := standard(date, u.URL); err != nil {
				return err
			}
		default:
			return fmt.Errorf("Unsupported type '%v'.\n", t)
		}
	}
	return nil
}

func today() string {
	currentTime := time.Now()
	currentDate := currentTime.Format("2006-01-02")
	dayMonthYear := currentTime.Format("02 Jan 2006")
	return "^(" + currentDate + "T" + allDayHours + "|.*" + dayMonthYear + " " + allDayHours + "):.*$"
}

func main() {
	date := flag.String("date", "", "Get the RSS feeds from a certain date: '^(2020-06-26T[0-2][0-9]|.*26 Jun 2020 [0-2][0-9]).*$'")
	input := flag.String("file", "informado.csv", "The file that contains a list of RSS URLs")

	if *date == "" {
		*date = today()
	}

	flag.Parse()

	urls, err := csv(*input)
	if err != nil {
		log.Fatal(err)
	}

	if err := read(urls, *date); err != nil {
		log.Fatal(err)
	}
}
