package main

import (
	"flag"
	"fmt"
	"informado/news"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strconv"
	"sync"
	"time"

	"github.com/gocarina/gocsv"
)

const (
	allDayHours = "[0-2][0-9]"
)

func readURL(u string) ([]byte, error) {
	var bodyBytes []byte

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	req, err := http.NewRequest("GET", u, nil)
	if err != nil {
		return nil, err
	}

	// Required to parse Reddit feeds
	req.Header.Set("user-agent", "hello:world:v0.0 (by /u/ocelost)")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	//https://stackoverflow.com/a/38673698/2777965
	if resp.StatusCode == http.StatusOK {
		bodyBytes, err = ioutil.ReadAll(resp.Body)
		if err != nil {
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("StatusCode not 200, but '%v'", resp.StatusCode)
	}
	return bodyBytes, nil
}

func rss(r news.RSS, url string) error {
	byte, err := readURL(url)
	if err != nil {
		return err
	}
	a, err := r.Parse(byte)
	if err != nil {
		return err
	}
	if err := a.Print(); err != nil {
		return err
	}
	return nil
}

type RSSFeeds struct {
	Type  string `csv:"type"`
	URL   string `csv:"url"`
	Error error
}

func csv(f string) ([]*RSSFeeds, error) {
	u, err := os.OpenFile(f, os.O_RDWR|os.O_CREATE, os.ModePerm)
	if err != nil {
		return nil, err
	}
	defer u.Close()

	r := []*RSSFeeds{}
	if err := gocsv.UnmarshalFile(u, &r); err != nil {
		return nil, err
	}

	return r, err
}

var wg sync.WaitGroup

func newsItems(c chan *RSSFeeds, r *RSSFeeds) {
	defer wg.Done()
	var e error

	switch t := r.Type; t {
	case "atom":
		if err := rss(news.Atom{}, r.URL); err != nil {
			e = err
		}
	case "standard":
		if err := rss(news.Standard{}, r.URL); err != nil {
			e = err
		}
	default:
		e = fmt.Errorf("Unsupported type '%v'", t)
	}

	c <- &RSSFeeds{r.Type, r.URL, e}
}

func read(urls []*RSSFeeds) error {
	c := make(chan *RSSFeeds, len(urls))
	for _, a := range urls {
		wg.Add(1)
		go newsItems(c, a)
	}
	wg.Wait()
	close(c)
	for item := range c {
		if item.Error != nil {
			return fmt.Errorf("Type: '%v'. URL: '%v', Err: '%v'", item.Type, item.URL, item.Error)
		}
	}
	return nil
}

func parse(input string) error {
	urls, err := csv(input)
	if err != nil {
		return err
	}
	if err := read(urls); err != nil {
		return err
	}
	return nil
}

func currentTimeToDisk() error {
	now := time.Now()
	epoch := now.Unix()

	file, err := os.Create(".informado")
	if err != nil {
		return err
	}
	defer file.Close()

	_, err = file.WriteString(strconv.FormatInt(epoch, 10))
	if err != nil {
		return err
	}

	return nil
}

func main() {
	input := flag.String("file", "informado.csv", "The file that contains a list of RSS URLs")

	flag.Parse()

	if err := parse(*input); err != nil {
		log.Fatal(err)
	}

	if err := currentTimeToDisk(); err != nil {
		log.Fatal(err)
	}
}
