---
apiVersion: v1
kind: Namespace
metadata:
  name: informado
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: informado
  namespace: informado
data:
  rss-feed-urls.csv: |-
    ---
    type,url
    atom,http://blog.golang.org/feed.atom
    atom,https://github.com/aws/aws-cli/releases.atom
    atom,https://github.com/golang/go/releases.atom
    atom,https://github.com/securego/gosec/releases.atom
    atom,https://github.com/kubernetes/kubernetes/releases.atom
    standard,https://aws.amazon.com/blogs/devops/feed
    standard,https://aws.amazon.com/new/feed
    standard,https://docker-hub-rss.now.sh/grafana/grafana.atom?includeRegex=%5E(%5Cd%2B%5C.)%7B2%7D%5Cd%2B%24
    standard,https://kubernetes.io/feed.xml
    standard,https://www.docker.com/blog/feed
---
apiVersion: v1
kind: Secret
metadata:
  name: informado
  namespace: informado
stringData:
  creds.yml: |-
    ---
    slack_channel_id: some-id
    slack_token: some-token
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: informado
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  hostPath:
    path: /var/k8s-storage/informado
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: informado
  namespace: informado
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  volumeName: informado
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: informado
  namespace: informado
spec:
  schedule: "*/15 6-22 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          containers:
            - name: informado
              image: utrecht/informado:3.1.0
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "25m"
                requests:
                  memory: "4Mi"
                  cpu: "5m"
              imagePullPolicy: IfNotPresent
              command:
                - informado
              args:
                - image
                - --home
                - /tmp/informado-config-creds
              volumeMounts:
                - name: creds-and-config
                  mountPath: /tmp/informado-config-creds/.informado
                  readOnly: true
                - mountPath: /tmp/informado
                  name: informado
          restartPolicy: OnFailure
          volumes:
            - name: informado
              persistentVolumeClaim:
                claimName: informado
            - name: creds-and-config
              projected:
                defaultMode: 420
                sources:
                  - secret:
                      name: informado
                  - configMap:
                      name: informado
