name: informado # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Stay informed using Informado # 79 char long summary
description: |
  Use this Go library or the tool to read various RSS feeds. Note that Atom and Reddit feeds can be
  parsed as well.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  informado:
    command: informado

plugs:
  informado-home:
    interface: home
  informado-network:
    interface: network

parts:
  informado:
    plugin: go
    source: .
    go-importpath: github.com/030/informado
