---
name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            nexus-version: 3.9.0
            nexus-api-version: beta
            shasum: shasum -a 512
          - os: ubuntu-20.04
            nexus-version: 3.30.0
            nexus-api-version: v1
            shasum: sha512sum
          - os: ubuntu-20.04
            nexus-version: 3.9.0
            nexus-api-version: beta
            shasum: sha512sum
          - os: windows-2019
            nexus-version: 3.9.0
            nexus-api-version: beta
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - name: Unit tests
        run: go test ./... -cover
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Install bats
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install bats -y
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Set N3DR deliverable environment variable
        run: echo "informado-deliverable=informado-${{ matrix.os }}" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.informado-deliverable }}"
      - name: Build
        run: ./scripts/build.sh
        env:
          N3DR_DELIVERABLE: ${{ env.informado-deliverable }}
          SHA512_CMD: ${{ matrix.shasum }}
      - name: Quality
        run: |
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:v0.7.1 */*.sh -x
          docker run --rm -v ${PWD}:/data markdownlint/markdownlint:0.11.0 \
            README.md -s /data/.markdownlint.rb
          docker run --rm -v $(pwd):/data cytopia/yamllint:1.26-0.8 .
          docker run --rm -v $(pwd):/app -w /app \
            golangci/golangci-lint:v1.39.0-alpine golangci-lint run -v
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Integration test
        run: ./test/integration-tests.sh
        env:
          N3DR_DELIVERABLE: ${{ env.informado-deliverable }}
          NEXUS_VERSION: ${{ matrix.nexus-version }}
          NEXUS_API_VERSION: ${{ matrix.nexus-api-version }}
          N3DR_APT_GPG_SECRET: ${{ secrets.N3DR_APT_GPG_SECRET }}
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
